# Generated by Django 4.1.5 on 2023-11-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major1',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='major1',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=20),
        ),
    ]
