# Generated by Django 4.2.7 on 2023-11-27 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="member_major_1",
            new_name="app_major_1",
        ),
    ]
