# Generated by Django 4.2.7 on 2023-11-27 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_member_major_1_member_app_major_1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="app_major_1",
            new_name="member_major_1",
        ),
    ]
