# Generated by Django 4.2.7 on 2023-11-27 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_app_major_1_member_member_major_1"),
        ("app", "0005_alter_member_member_friends_alter_member_member_like_and_more"),
    ]

    operations = []
